version: '2'
volumes:
    greenwood.deakin.edu.au: null
    peer0.peer.example.com: null
    peer1.peer.example.com: null
networks:
    fn: null
services:
    greenwood.deakin.edu.au:
        container_name: greenwood.deakin.edu.au
        image: 'hyperledger/fabric-orderer:$IMAGE_TAG'
        environment:
            - FABRIC_LOGGING_SPEC=DEBUG
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - 'ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]'
            - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
            - ORDERER_KAFKA_VERBOSE=true
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        volumes:
            - './channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block'
            - './crypto-config/ordererOrganizations/deakin.edu.au/orderers/greenwood.deakin.edu.au/msp:/var/hyperledger/orderer/msp'
            - './crypto-config/ordererOrganizations/deakin.edu.au/orderers/greenwood.deakin.edu.au/tls/:/var/hyperledger/orderer/tls'
            - 'greenwood.deakin.edu.au:/var/hyperledger/production/orderer'
        ports:
            - '7050:7050'
        networks:
            - fn
    peer0.peer.example.com:
        container_name: peer0.peer.example.com
        extends:
            file: base/peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.peer.example.com
            - 'CORE_PEER_ADDRESS=peer0.peer.example.com:7051'
            - 'CORE_PEER_GOSSIP_BOOTSTRAP=peer1.peer.example.com:7051'
            - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.peer.example.com:7051'
            - CORE_PEER_LOCALMSPID=TestPeerMSP
        volumes:
            - '/var/run/:/host/var/run/'
            - './crypto-config/peerOrganizations/peer.example.com/peers/peer0.peer.example.com/msp:/etc/hyperledger/fabric/msp'
            - './crypto-config/peerOrganizations/peer.example.com/peers/peer0.peer.example.com/tls:/etc/hyperledger/fabric/tls'
            - 'peer0.peer.example.com:/var/hyperledger/production'
        ports:
            - '7051:7051'
            - '7053:7053'
        networks:
            - fn
    peer1.peer.example.com:
        container_name: peer1.peer.example.com
        extends:
            file: base/peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer1.peer.example.com
            - 'CORE_PEER_ADDRESS=peer1.peer.example.com:7051'
            - 'CORE_PEER_GOSSIP_BOOTSTRAP=peer0.peer.example.com:7051'
            - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.peer.example.com:7051'
            - CORE_PEER_LOCALMSPID=TestPeerMSP
        volumes:
            - '/var/run/:/host/var/run/'
            - './crypto-config/peerOrganizations/peer.example.com/peers/peer1.peer.example.com/msp:/etc/hyperledger/fabric/msp'
            - './crypto-config/peerOrganizations/peer.example.com/peers/peer1.peer.example.com/tls:/etc/hyperledger/fabric/tls'
            - 'peer1.peer.example.com:/var/hyperledger/production'
        ports:
            - '8051:7051'
            - '8053:7053'
        networks:
            - fn
    cli:
        container_name: cli
        image: hyperledger/fabric-tools:$IMAGE_TAG
        tty: true
        stdin_open: true
        environment:
        - GOPATH=/opt/gopath
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        #- FABRIC_LOGGING_SPEC=DEBUG
        - FABRIC_LOGGING_SPEC=INFO
        - CORE_PEER_ID=cli
        - CORE_PEER_ADDRESS=peer0.peer.example.com:7051
        - CORE_PEER_LOCALMSPID=TestPeerMsp
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/peer.example.com/peers/peer0.peer.example.com/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/peer.example.com/peers/peer0.peer.example.com/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/peer.example.com/peers/peer0.peer.example.com/tls/ca.crt
        - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/peer.example.com/users/Admin@peer.example.com/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ./chaincode/:/opt/gopath/src/github.com/chaincode
            - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            #- ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        depends_on:
        - greenwood.deakin.edu.au
        - peer0.peer.example.com
        - peer1.peer.example.com
        networks:
        - fn
